# Generated by Django 2.0.6 on 2018-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_seed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mark',
            name='value',
            field=models.PositiveSmallIntegerField(choices=[(20, '2.0'), (30, '3.0'), (35, '3.5'), (40, '4.0'), (45, '4.5'), (50, '5.0')]),
        ),
    ]
